coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 75%
        threshold: 2%

ignore:
  - "client-go/examples/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false 